language: node_js
node_js:
- '5.0'
- '4.0'
- '4.1'
- '4.0'
- '0.12'
- '0.10'
services:
- mongodb
notifications:
  email: false
  slack:
    secure: fHop1QT6WlcI8QGG0tdrDKuSHDafXFupRyVbYSvql6mHwvN1YGuDaja7BuImwM1ozKwbdIM/O9sjhL5o9oFAmcjdq+Kjh3vpOhZ1pHuKUew2GmuZHZXU+sY6b6K2fNplE2zC8c84Z03LbG4gwqNTlRt/qRI3GT4fCTwEtt+7iAxC03qDRgRH/9OnPayYF0gUXPmtp0FIeAu0PUaLMMl/+MxOd/5ZPlE8v9gzeTv/BysdjzgWqau+SbQBlGG0YQxb8Vq4jlvykNEfYltx8SPVSkEEnBgeE9rYTfVn/urXG/YchKDdYtmSfLi1fXlPOFfUxhZAKLAAN2sQsPXlo847F4XZokN2A3761XXkmOUM+uRAYEsOMnkmqjDjP68Oi79Ccmo6lSlnoiZtBASo3WXeJVSnML8Sr4JtXOKrvsSsNycgSRDhj5K0XJlQPJlPwfzBMUH7gbC0z2RZo6/SLDYpVRN1tQW0F84aaQ6B9wyv0+eYw4lpylQqtwthZE9L4A4izNkVg+X9vmMeDwiykg7QvZjbmQPr5/DG3hsiWXvit6NHuJQw/nsk3F+9bYSo+9ADMh8kqVkTvfz07HUQnT7HTYIK2hk3S6T898Q0fBWDS5y2jLYG3Ya2H2tt0gyvvY5LZofLXLx0STUGS3mkqD2qIy7M53NQxYm2bhFflRsYMMM=
deploy:
  provider: npm
  email: jason@centralping.com
  api_key:
    secure: d2dbhoPFyhd2/F605wXumxP/mdcXqX4JBSny5TPbNdlFCYc4IwMa5+CF/C33LUbemeLErvTIX2DZgBFz7Lpa4Yf5iDO/2Rnfnm7wpTfKxomB7UxHRQLDl40hqNzwblNsCqfXE3xFBft1nBUW9RqF0Pa9q3zzaBIRBwQujHDVwRx8WE0pUEOLtMGcNHLtwxFFsGG7jM2CPZlVVVNZM2KkNC0gr8MyVpzcDa/9vACqedzipQPHD0aAiIr6bYNiC5Kf7BXj5dDnO7Ui3ffrUDKA+p9kD26FesNwwgmUlOuZ00ddwnFBspiUhfusEfSNv879GS9gUSOdN3/6KoPsp3nCTzSPNALAcBiHR21vGCJ6RTIYKXrypQaxevSIQXjksfrSETsFa46tq5dhM9y6eOSqqad2HZg1JnBXnkWT7TpFq3OLIjuGpdgESmIFnqLcbS85nGyOqneE3RLcfxoRJk0OFipDqslnnGgHCvDQSk/milYN3hw3MesiQJLP2aqAeNkXtoYZat4pEEfrmbkGY9e+U1EtGev0V7pdQSrfcvFK+Fh3ZfZ/5fuGNFDNUFLF7Inr76KUvQ5a5l69mJeBjrOcvFXLEM653RK95rG12g6maZx2jpJTwipBee+EBsYsIaSk3nSxx/zOnchXvz6qPY88xtpGqyfKt63Gj9+3kOeiMgg=
  on:
    tags: true
    repo: CentralPing/mongoose-plugin-auth
